[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.9

[font]
normal = { family = "Liberation Mono" }
bold = { family = "Liberation Mono", style = "Bold" }
italic = { family = "Liberation Mono", style = "Italic" }
bold_italic = { family = "Liberation Mono", style = "Bold Italic" }
size = 8.0

